title: Failure makes success.
author: 새미아빠
email: comsiro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  새미아빠의 블로그의 글들은 개인의 견해이며 글 내용에 대한 법적 책임을 지지 않습니다.
  
  글 퍼가기를 원하시면 사전에 새미아빠와 상의하세요.

text_current_post: 해당 카테고리의 최근 글

github_username:  comsiro

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Google services
google_analytics: UA-80294273-2

google_adsense: true

disqus:
  shortname: comsiro

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - gulpfile.js
